# Generated by Django 5.0.6 on 2024-05-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('one_hour_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('twenty_four_hour_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seven_day_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume_24h', models.DecimalField(decimal_places=2, max_digits=20)),
                ('circulating_supply', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
