# Generated by Django 5.0.6 on 2024-05-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='circulating_supply',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coin',
            name='market_cap',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coin',
            name='one_hour_change',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coin',
            name='price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coin',
            name='seven_day_change',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coin',
            name='twenty_four_hour_change',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coin',
            name='volume_24h',
            field=models.CharField(max_length=255),
        ),
    ]
